version: 6.0.{build}

image: Visual Studio 2017

init:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global lfs.https://github.com/emgre/projectmercury.git/info/lfs.access basic

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..
build_script:
  - cmake --build . --config Release