version: 6.0.{build}

image: Visual Studio 2017

clone_script:
- ps: >- 
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
      git clone --depth=1 -q -c filter.lfs.smudge= -c filter.lfs.required=false --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
      git config lfs.https://github.com/$env:APPVEYOR_REPO_NAME.git/info/lfs.access basic
      git lfs pull
    }
    else
    {
      git clone --depth=1 -q -c filter.lfs.smudge= -c filter.lfs.required=false git@github.com:$env:appveyor_repo_name.git $env:appveyor_build_folder
      git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
      git checkout -qf FETCH_HEAD
      git lfs pull 
    }

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..
build_script:
  - cmake --build . --config Release