#define IDB_MAINPANEL                   101
#define IDB_SWITCH                      102
#define IDB_BACKSEQUENCE                104
#define IDB_SEQSWITCH                   106
#define IDB_GLOBEPANEL                  107
#define IDB_EARTHGLOBE                  108
#define IDB_ABORT                       110
#define IDB_SEQLIGHT                    111
#define IDB_RINGSWITCH                  112
#define IDB_FLIGHTSWITCH                114
#define IDB_PULLHANDLE                  116
#define IDB_FLIGHTCONTROL               118
#define IDB_PUSHBUTTON                  120
#define IDB_RDGLOBEPANEL                125
#define IDB_RETRONUMBERS                127
#define IDB_RETROHANDLEINCMIN           128
#define IDB_RETROHANDLEINCSEC           129
#define IDB_RETROHANDLEOFF              130
#define IDB_RETROWARN                   134
#define IDB_RETROGRADEPANEL             135
#define IDB_PUSHBUTTON_FLIGHT           137
#define IDB_RETROHANDLEDECMIN           138
#define IDB_RETROHANDLEDECSEC           139
#define IDB_REPRESS_HANDLE              142
#define IDB_DECOMP_HANDLE               143
#define IDB_PERISCOPE                   145
#define IDB_ALT_KNOB                    146
#define IDB_FLIGHTCONTROL7              149
#define IDB_FUSEPANEL                   150
#define IDB_RIGHTPANEL                  151
#define IDB_KNOBAC                      152
#define IDB_KNOBDC                      153
#define IDB_FUSESWITCHSTRIP             154
#define IDB_FUSESWITCHWHITE             155
#define IDB_WARNLIGHTS                  156
#define IDB_CAMERAPANEL                 158
